name: Node Azure CI/CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test --if-present

      - name: Login to Azure Container Registry
        uses: docker/login-action@v4
        with:
          registry: abhisheknodeacr2026-bah3gxf2a0cveubf.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            abhisheknodeacr2026-bah3gxf2a0cveubf.azurecr.io/node-api:latest
            abhisheknodeacr2026-bah3gxf2a0cveubf.azurecr.io/node-api:${{ github.sha }}